  name: Build Docker
    description: Build Docker
  runs:
  -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      -
          name: Login to DockerHub
          uses: docker/login-action@v2
          with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
      -