name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          password: ${{ secrets.DOCKER_PERSONAL_ACCESS_TOKEN }}
          username: ${{ secrets.DOCKER_USERNAME }}
          ecr: false
      - name: Build Tag and Push Docker Image
        run: |-
          echo "-1---------------------------"
          pwd
          ls -alh
          echo "-2---------------------------"
          docker build \
            --file Dockerfile \
            -t docker.io/${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:$GITHUB_SHA \
            -t docker.io/${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest \
            -t docker.io/${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:0.0.1 \
            .
          docker push -a \
            docker.io/${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}