name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          password: ${{ secrets.DOCKER_PERSONAL_ACCESS_TOKEN }}
          username: ${{ secrets.DOCKER_USERNAME }}
          ecr: false
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |-
          echo "-1---------------------------"
          pwd
          ls -alh
          echo "-2---------------------------"
          docker build . \
            --file Dockerfile \
            --tag docker.io/${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:$GITHUB_SHA
          docker push \
            docker.io/${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:$GITHUB_SHA